# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/platform/build-configuration

[build]
command = "bun install && bun run build"
output_directory = "dist"

[build.environment]
NODE_VERSION = "20"
